<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPBYMINW2705" name="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos" tests="18" failures="0" timestamp="23 Jun 2017 13:15:35 GMT" time="0.048" errors="2">
  <testcase name="checkResolveValidValue" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveValidValue" time="0.000" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchArithmeticExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchIllegalArgExpIncorrectValues" time="0.005" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchIllegalArgExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchArithmeticExpIncorrectValues" time="0.003" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchArithmeticExpIncorrectValues" time="0.011" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchIllegalArgExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchArithmeticExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchArithmeticExpValidValues" time="0.006" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchIllegalArgExpIncorrectValues" time="0.005" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchIllegalArgExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveNOCatchIllegalArgExpValidValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchIllegalArgExpIncorrectValues" time="0.004" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchArithmeticExpIncorrectValues" time="0.002" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveValidValue" time="0.000" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos"/>
  <testcase name="checkResolveCatchArithmeticExpIncorrectValues" time="0.004" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos">
    <error type="org.testng.TestException" message="
Method Tst0201ExpressionResolveIllegalArgExpPos.checkResolveCatchArithmeticExpIncorrectValues(double, double, double)[pri:0, instance:tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos@b97c004] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method Tst0201ExpressionResolveIllegalArgExpPos.checkResolveCatchArithmeticExpIncorrectValues(double, double, double)[pri:0, instance:tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos@b97c004] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- checkResolveCatchArithmeticExpIncorrectValues -->
  <testcase name="checkResolveCatchIllegalArgExpIncorrectValues" time="0.001" classname="tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos">
    <error type="org.testng.TestException" message="
Method Tst0201ExpressionResolveIllegalArgExpPos.checkResolveCatchIllegalArgExpIncorrectValues(double, double, double)[pri:0, instance:tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos@b97c004] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method Tst0201ExpressionResolveIllegalArgExpPos.checkResolveCatchIllegalArgExpIncorrectValues(double, double, double)[pri:0, instance:tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos@b97c004] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- checkResolveCatchIllegalArgExpIncorrectValues -->
</testsuite> <!-- tests.task0102.Tst0201ExpressionResolveIllegalArgExpPos -->
