<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPBYMINW2705" name="tests.task0105.Tst0501Pow" tests="9" failures="0" timestamp="23 Jun 2017 13:44:30 GMT" time="0.072" errors="1">
  <testcase name="pow_IncorrectValues" time="0.017" classname="tests.task0105.Tst0501Pow">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: pow_IncorrectValues([Parameter{index=0, type=double, declaredAnnotations=[]}, Parameter{index=1, type=double, declaredAnnotations=[]}, Parameter{index=2, type=double, declaredAnnotations=[]}, Parameter{index=3, type=[D, declaredAnnotations=[]}])
Arguments: [(java.lang.Double)Infinity,(java.lang.Double)Infinity,(java.lang.Double)Infinity]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: pow_IncorrectValues([Parameter{index=0, type=double, declaredAnnotations=[]}, Parameter{index=1, type=double, declaredAnnotations=[]}, Parameter{index=2, type=double, declaredAnnotations=[]}, Parameter{index=3, type=[D, declaredAnnotations=[]}])
Arguments: [(java.lang.Double)Infinity,(java.lang.Double)Infinity,(java.lang.Double)Infinity]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- pow_IncorrectValues -->
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.048" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
  <testcase name="pow_ValidValues" time="0.001" classname="tests.task0105.Tst0501Pow"/>
</testsuite> <!-- tests.task0105.Tst0501Pow -->
